// Available Lucide icons for modules and stages
import {
  Zap,
  Code,
  Rocket,
  Target,
  Shield,
  Cog,
  Database,
  Cloud,
  Users,
  GitBranch,
  BarChart3,
  Lock,
  AlertCircle,
  CheckCircle,
  Clock,
  Archive,
  Brain,
  Bug,
  Beaker,
  Gauge,
  Cpu,
  Wrench,
  Layers,
  Monitor,
  FileText,
  Box,
  TrendingUp,
  Palette,
  BookOpen,
  Eye,
  Star,
  Lightbulb,
  Trophy,
  Server,
  Smartphone,
  GitMerge,
  RefreshCw,
  Workflow,
  TestTube,
  Compass,
} from 'lucide-react'

export const AVAILABLE_ICONS = [
  { name: 'Zap', icon: Zap, label: 'Flash' },
  { name: 'Code', icon: Code, label: 'Code' },
  { name: 'Rocket', icon: Rocket, label: 'Rocket' },
  { name: 'Target', icon: Target, label: 'Target' },
  { name: 'Shield', icon: Shield, label: 'Security' },
  { name: 'Cog', icon: Cog, label: 'Settings' },
  { name: 'Database', icon: Database, label: 'Database' },
  { name: 'Cloud', icon: Cloud, label: 'Cloud' },
  { name: 'Users', icon: Users, label: 'Team' },
  { name: 'GitBranch', icon: GitBranch, label: 'Git Branch' },
  { name: 'BarChart3', icon: BarChart3, label: 'Analytics' },
  { name: 'Lock', icon: Lock, label: 'Lock' },
  { name: 'AlertCircle', icon: AlertCircle, label: 'Alert' },
  { name: 'CheckCircle', icon: CheckCircle, label: 'Check' },
  { name: 'Clock', icon: Clock, label: 'Schedule' },
  { name: 'Archive', icon: Archive, label: 'Archive' },
  { name: 'Brain', icon: Brain, label: 'Planning' },
  { name: 'Bug', icon: Bug, label: 'Bug Fix' },
  { name: 'Beaker', icon: Beaker, label: 'Research' },
  { name: 'Gauge', icon: Gauge, label: 'Performance' },
  { name: 'Cpu', icon: Cpu, label: 'Infrastructure' },
  { name: 'Wrench', icon: Wrench, label: 'Maintenance' },
  { name: 'Layers', icon: Layers, label: 'Architecture' },
  { name: 'Monitor', icon: Monitor, label: 'Monitor' },
  { name: 'FileText', icon: FileText, label: 'Documentation' },
  { name: 'Box', icon: Box, label: 'Deployment' },
  { name: 'TrendingUp', icon: TrendingUp, label: 'Growth' },
  { name: 'Palette', icon: Palette, label: 'Design' },
  { name: 'BookOpen', icon: BookOpen, label: 'Learning' },
  { name: 'Eye', icon: Eye, label: 'Review' },
  { name: 'Star', icon: Star, label: 'Featured' },
  { name: 'Lightbulb', icon: Lightbulb, label: 'Idea' },
  { name: 'Trophy', icon: Trophy, label: 'Achievement' },
  { name: 'Server', icon: Server, label: 'Backend' },
  { name: 'Smartphone', icon: Smartphone, label: 'Frontend' },
  { name: 'GitMerge', icon: GitMerge, label: 'Merge' },
  { name: 'RefreshCw', icon: RefreshCw, label: 'Update' },
  { name: 'Workflow', icon: Workflow, label: 'Workflow' },
  { name: 'TestTube', icon: TestTube, label: 'Testing' },
  { name: 'Compass', icon: Compass, label: 'Navigation' },
]

export function getIconByName(name?: string) {
  if (!name) return null
  const iconData = AVAILABLE_ICONS.find((i) => i.name === name)
  return iconData?.icon || null
}

export function getIconLabel(name?: string) {
  if (!name) return ''
  const iconData = AVAILABLE_ICONS.find((i) => i.name === name)
  return iconData?.label || name
}
